-- MySQL Script generated by MySQL Workbench
-- Fri May 20 01:26:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema disney
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema disney
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `disney` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `disney` ;

-- -----------------------------------------------------
-- Table `disney`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disney`.`genero` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  `pelicula/serie` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pelicula/serie_UNIQUE` (`pelicula/serie` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `imagen_UNIQUE` (`imagen` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `disney`.`pelicula/serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disney`.`pelicula/serie` (
  `id` INT NOT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `fecha de creacion` DATETIME NOT NULL,
  `calificacion` INT NOT NULL,
  `personajes asociados` VARCHAR(45) NOT NULL,
  `Genero_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Genero_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `titulo_UNIQUE` (`titulo` ASC),
  UNIQUE INDEX `fecha de creacion_UNIQUE` (`fecha de creacion` ASC),
  UNIQUE INDEX `imagen_UNIQUE` (`imagen` ASC),
  INDEX `fk_Pelicula/Serie_Genero1_idx` (`Genero_id` ASC),
  CONSTRAINT `fk_Genero_id`
    FOREIGN KEY (`Genero_id`)
    REFERENCES `disney`.`genero` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `disney`.`personaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disney`.`personaje` (
  `id` INT NOT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `edad` INT NOT NULL,
  `peso` INT NULL DEFAULT NULL,
  `historia` VARCHAR(255) NOT NULL,
  `pelicula/serie` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `edad_UNIQUE` (`edad` ASC),
  UNIQUE INDEX `pelicula/serie_UNIQUE` (`pelicula/serie` ASC),
  UNIQUE INDEX `imagen_UNIQUE` (`imagen` ASC),
  UNIQUE INDEX `peso_UNIQUE` (`peso` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `disney`.`personaje_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disney`.`personaje_detail` (
  `Personaje_id` INT NOT NULL,
  `Pelicula/Serie_id` INT NOT NULL,
  PRIMARY KEY (`Personaje_id`, `Pelicula/Serie_id`),
  INDEX `fk_Personaje_has_Pelicula/Serie_Pelicula/Serie1_idx` (`Pelicula/Serie_id` ASC),
  INDEX `fk_Personaje_has_Pelicula/Serie_Personaje_idx` (`Personaje_id` ASC),
  CONSTRAINT `fk_Personaje_has_Pelicula/Serie_Pelicula/Serie1`
    FOREIGN KEY (`Pelicula/Serie_id`)
    REFERENCES `disney`.`pelicula/serie` (`id`),
  CONSTRAINT `fk_Personaje_has_Pelicula/Serie_Personaje`
    FOREIGN KEY (`Personaje_id`)
    REFERENCES `disney`.`personaje` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
